name: app 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: 0.20.5
  hooks_riverpod: 2.5.2
  riverpod_annotation: 2.3.5

  graphql_flutter: 5.2.0-beta.7
  graphql: 5.2.0-beta.9

  devtools_extensions: 0.2.2
  devtools_app_shared: 0.2.2

  skeletonizer: 1.4.2

  gql_dio_link: 1.0.1+1
  dio: 5.7.0
  pretty_dio_logger: 1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.4.3
  graphql_codegen: 1.0.1
  build_runner: 2.4.13

flutter:
  uses-material-design: true

