name: devtools_ext
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter

  # For DevTools
  devtools_extensions: 0.2.2
  devtools_app_shared: 0.2.2

  # For Architecture
  flutter_hooks: 0.20.5

  # For UI
  gap: 3.0.1

  app:
    path: ../app

flutter:
  uses-material-design: true

